name: Self-Hosted Runner Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
    

jobs:
  build:
    runs-on: self-hosted  # Use your self-hosted runner
    steps:
      - name: Build and Test
        run: echo "Your build and test goes here..."
  security-scan:
    runs-on: self-hosted
    steps:
      # - uses: actions/checkout@v4 new restart
      - name: Security Scanner
        run: echo "Your security scan goes here..."
      - name: Transition Jira Issue
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        # run:  echo "SECRET ${{ secrets.JIRA_API_TOKEN }}"
        run: |
          curl -X GET -H "Content-Type: application/json" -u "ary.suwandi@izeno.com:ATATT3xFfGF0bS5kr_GhBXwjOsxyObMT-1faJKR8AthR3JAWE9D2YUcB1AiBmuYNLlyAiJM3eB_L-nK80h2D7cfqMv9_pxF7ne66qMKDzRIDCbTZM98gfhOa6Xt1JGXBrIeBBRVEWS7qvWtKhzFg71ufSvjgRYZ7h5o7Zc5foXK83iYDuuPUf6U=0E1C0C0B" "https://izeno-rovo.atlassian.net/rest/api/3/issue/GITHUB-3/transitions"
        # run: |
        #   curl -request POST \
        #   --url "https://izeno-rovo.atlassian.net/rest/api/3/issue/GITHUB-3/transitions" \ 
        #   --header "Accept: application/json" \
        #   --header "Content-Type: application/json" \
        #   --user "ary.suwandi@izeno.com:ATATT3xFfGF0yWKsASkk0np01gDTS7Ca8vSsdiFKC_jfzjHQjDwL_plX0X-u1kbSZbry_JnxGwHfHxha9ecMYfXAEgsKE2YUkZB99m-t7L_V647AwuGr_hGHd_9UT7JvuYNsJqX1yxQM-ADaifcgnsvAerc5M2pgskG8bJZyjsTvi5FLQONBanQ=E1292D20" \
        #   --data '{"transition": {"name": "In Progress"}}'
      # - name: Checkout code
      #   uses: actions/checkout@v2

      # - name: Run a script
      #   run: echo "Running on a self-hosted runner SIMPLE_YAML!"
    # steps:
    #   - name: 'Security scanner'
    #       script:
    #       - echo "Your security scan goes here..."
    #       # - LAST_COMMIT_MESSAGE=$(git log -n 1 --pretty=format:%s $BITBUCKET_COMMIT)
    #       - pipe: atlassian/jira-transition:0.2.4