name: Self-Hosted Runner Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
    

jobs:
  build:
    runs-on: self-hosted  # Use your self-hosted runner
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v2

      - name: Run a script
        run: echo "Running on a self-hosted runner SIMPLE_YAML!"