name: Self-Hosted Runner Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
    

jobs:
  build:
    runs-on: self-hosted  # Use your self-hosted runner
    steps:
      - name: Build and Test
        run: echo "Your build and test goes here..."
  security-scan:
    runs-on: self-hosted
    steps:
      # - uses: actions/checkout@v4
      - name: Security Scanner
        run: echo "Your security scan goes here..."
      - name: Transition Jira Issue
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        run:  echo "SECRET ${JIRA_API_TOKEN}"
        # run: |
        #   LAST_COMMIT_MESSAGE=$(git log -n 1 --pretty=format:%s ${{ github.sha }})
        #   curl -X POST -H "Content-Type: application/json" \
        #        -u "${JIRA_USER_EMAIL}:${JIRA_API_TOKEN}" \
        #        "${JIRA_BASE_URL}/rest/api/3/issue/GITHUB-3/transitions" \
        #        -d '{"transition": {"name": "In Progress"}}'
      # - name: Checkout code
      #   uses: actions/checkout@v2

      # - name: Run a script
      #   run: echo "Running on a self-hosted runner SIMPLE_YAML!"
    # steps:
    #   - name: 'Security scanner'
    #       script:
    #       - echo "Your security scan goes here..."
    #       # - LAST_COMMIT_MESSAGE=$(git log -n 1 --pretty=format:%s $BITBUCKET_COMMIT)
    #       - pipe: atlassian/jira-transition:0.2.4